### ISSUE TITLE
Dependency not working..Lib works

### ISSUE THREAD

**Issue by YudizKhushbu** [pedromassango/IBackdrop#2]
dependency in a project isn't working as I am using 3.3 (preview) version with kotlin support of 1.2.50 as well as min SDK version 16+..But when I manually put lib ..it;s working!

**Comment by pedromassango** [comment]
Hi @YudizKhushbu have you set this line in your **build.gradle** project level:
**maven { url 'https://jitpack.io' }** if do not, please add it, and let me know.

**Comment by pedromassango** [comment]
I'm currently using it in a project, and it works fine.
