### ISSUE TITLE
Medium Documentation Page is `Suspended`

### ISSUE THREAD

**Issue by arsensaruhanyan2611** [pedromassango/IBackdrop#4]
While I click bit.ly button, I get only 'This page is unavailable'. Please fix it.

**Comment by pedromassango** [comment]
Thanks, I fixed it. You can also click on this link:

https://blog.usejournal.com/android-material-design-components-backdrop-96a3044a3b2

**Comment by clevermatem** [comment]
still suspended medium article

**Comment by pedromassango** [comment]
Sorry for that. My account was supended with no reason and all my articles are gone for the public
