### ISSUE TITLE
Hi.. why're condsidering that to use backdrop you must have toolbar widget because I have my custom toolbar which made up of CardView for that reason I wasn't able to use the library

### ISSUE THREAD

**Issue by vipafattal** [pedromassango/IBackdrop#9]

**Comment by pedromassango** [comment]
You can use a custom toolbar just provide your toolbar's Id. Check this post:
https://blog.usejournal.com/android-material-design-components-backdrop-96a3044a3b2

**Comment by pedromassango** [comment]
I'm going to support a custom Toolbar as a toolbar, for now you must provide a valid toolbar.

**Comment by vipafattal** [comment]
Oh Thanks.
The problem I don't have Toolbar at all in my layout instead I want to connect my CardView (which act just like Toolbar in my app) with the backdrop

**Comment by pedromassango** [comment]
Noted, I'm going to support a custom Toolbar as a toolbar in a later version

**Comment by pedromassango** [comment]
Hi @vipafattal I just made it work without a Toolbar. Now just don't give it the toolbar id or use the toolbar function. 

If you want to open or close the Backdrop just call the `backdrop_view.open()` or `backdrop_view.close()` function.

The commit of this change:
https://github.com/pedromassango/IBackdrop/commit/9cb46640d01f964421bba99e3b29af21e94e1489
